# Generated by Django 5.0.4 on 2024-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчина'), ('woman', 'Женщина'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Пол'),
        ),
    ]
