# Generated by Django 5.0.4 on 2024-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления профиля'),
        ),
    ]
